### ISSUE TITLE
解除dapper的依赖

### ISSUE THREAD

**Issue by mbpframework** [ShiWei-L/NlogDashboard#61]
因为dapper是个比较常用的依赖，可能会和其他第三方组件造成版本上的冲突，解决方案虽然有，但是不好看

**Comment by realLiangshiwei** [comment]
我也在考虑减少依赖，也许会去除更多的依赖

**Comment by realLiangshiwei** [comment]
移至: https://github.com/realLiangshiwei/LogDashboard/issues/84
