### ISSUE TITLE
日志文件放在部署站点目录之外，无法读取到日志

### ISSUE THREAD

**Issue by mcjing** [ShiWei-L/NlogDashboard#62]
比如我的站点的位置是 D:/NET_CORE  ,日志文件记录在D:/LOG  
如果是上述的这种情况，LogDashboard页面无法显示日志文件的内容

**Comment by realLiangshiwei** [comment]
`context.Services.AddLogDashboard(opt => opt.SetRootPath(your log path));`

https://github.com/realLiangshiwei/LogDashboard/blob/fb36e15994df7c851054d9ded6e8e16980ebbc51/src/LogDashboard/Extensions/LogDashboardOptionsExtensions.cs#L10
