### ISSUE TITLE
使用非默认路由时 会导致UI 样式js文件加载404

### ISSUE THREAD

**Issue by Corps-Cy** [ShiWei-L/NlogDashboard#63]
![QQ图片20210126131408](https://user-images.githubusercontent.com/38969961/105803447-75459080-5fd8-11eb-8376-e4226717aee1.png)

app.UseLogDashboard("/log");

**Comment by realLiangshiwei** [comment]
```csharp            
services.AddLogDashboard(opt =>
{
     opt.PathMatch  = "/log";
});
```
https://github.com/realLiangshiwei/LogDashboard/blob/6b920e9f3525d01e35b1066dd45a061528539ca9/src/LogDashboard/LogDashboardOptions.cs#L23

**Comment by linkxu1989** [comment]
Version 1.4.7
IIS site name: Default Web Site/AEMS
Destination URL: 10.48.2.20/AEMS
How to change the PathMarch, it doesn't work when I changed it like this.
services.AddLogDashboard(opt =>
{
     opt.PathMatch  = "/log";
});
