### ISSUE TITLE
为什么不支持Logger的筛选过滤？

### ISSUE THREAD

**Issue by git102347501** [ShiWei-L/NlogDashboard#64]
![image](https://user-images.githubusercontent.com/37917403/108821614-d624b080-75f8-11eb-96c6-0eefed90ca84.png)
希望支持Logger的过滤条件

**Comment by realLiangshiwei** [comment]
可以放到合并条件到message中, 下个版本支持.

**Comment by git102347501** [comment]
这块加个json配置比较灵活一点

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/LogDashboard/commit/75fe55e9ee845a7524724bea149490e0d61b649e
