### ISSUE TITLE
.net core 3.1 读取log4net的 日志文件中文乱码

### ISSUE THREAD

**Issue by 13640535881** [ShiWei-L/NlogDashboard#69]
.net core 3.1 读取log4net的 日志文件中文乱码

**Comment by realLiangshiwei** [comment]
无法复现

![image](https://user-images.githubusercontent.com/16813853/115713099-34c39c00-a3a8-11eb-8504-ae30f2328038.png)

**Comment by 13640535881** [comment]
排查了半天，确实是自己的问题 ：） 

原因是在program.cs中，配置了webhost的默认编码
.ConfigureWebHostDefaults(webBuilder =>
 {
          ////注册编码扩展以支持GB2312
          //System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
          webBuilder.UseStartup<Startup>();
});

**Comment by 13640535881** [comment]
但还发现一个问题：
自定义路由的情况，会出现页面不正常，样式无法加载，跳转找不到路由地址
app.UseLogDashboard("/logs");
![U A2O}LPBR4URJNPO(1D(GS](https://user-images.githubusercontent.com/55781372/115822916-ef4eaf80-a437-11eb-8c24-5d11129a0e80.png)

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/LogDashboard/blob/2a2821e2ddbfdad20056135f7894cedcd4befc2e/src/LogDashboard/LogDashboardOptions.cs#L23

```csharp
services.AddLogDashboard(opt =>
{
      opt.PathMatch  = "xxx"
});
```

**Comment by 13640535881** [comment]
好的，谢谢
