### ISSUE TITLE
项目没发布到IIS根目录，加载不出来呢？

### ISSUE THREAD

**Issue by linkxu1989** [ShiWei-L/NlogDashboard#72]
路径如： http://10.48.2.20/AEMS/logdashboard， AEMS不在Default Web Site, 而是是在Default Web Site/AEMS.

![Issue about display](https://user-images.githubusercontent.com/17608441/115993460-6d13e600-a605-11eb-9b00-c4d0d67cde4f.jpg)

**Comment by realLiangshiwei** [comment]
js,css路径不对，你要改一下。 https://github.com/realLiangshiwei/LogDashboard/issues/63

**Comment by realLiangshiwei** [comment]
看你的请求路径，我也不知道你的项目什么情况

**Comment by linkxu1989** [comment]
If I just use services.AddLogDashboard(), there're many 404; 

then, when I added the pathmatch,
services.AddLogDashboard(opt =>
            {
                opt.PathMatch = "/AEMS";
            });
Uncaught ReferenceError: value is not defined
    at js.jquery.min.js:1
(anonymous) @ js.jquery.min.js:1
js.Chart.min.js:1 Uncaught ReferenceError: value is not defined
    at js.Chart.min.js:1
(anonymous) @ js.Chart.min.js:1
js.bootstrap.min.js:1 Uncaught ReferenceError: value is not defined
    at js.bootstrap.min.js:1
(anonymous) @ js.bootstrap.min.js:1
js.moment.min.js:1 Uncaught ReferenceError: value is not defined
    at js.moment.min.js:1
(anonymous) @ js.moment.min.js:1
js.tempusdominus-bootstrap-4.js:1 Uncaught ReferenceError: value is not defined
    at js.tempusdominus-bootstrap-4.js:1
(anonymous) @ js.tempusdominus-bootstrap-4.js:1
js.spin.min.js:1 Uncaught ReferenceError: value is not defined
    at js.spin.min.js:1
(anonymous) @ js.spin.min.js:1
js.log.js:1 Uncaught ReferenceError: value is not defined
    at js.log.js:1
(anonymous) @ js.log.js:1
js.home.js:1 Uncaught ReferenceError: value is not defined
    at js.home.js:1
(anonymous) @ js.home.js:1
logdashboard:192 Uncaught ReferenceError: logInfo is not defined
    at HTMLAnchorElement.onclick (logdashboard:192)

**Comment by realLiangshiwei** [comment]
For example: `http://10.48.2.20/AEMS/logdashboard`

```csharp
  opt.PathMatch = "AEMS/logdashboard";
```

**Comment by linkxu1989** [comment]
It is working properly, thanks!
opt.PathMatch = "/AEMS/logdashboard";
