### ISSUE TITLE
Could not found JS with 404 when published to IIS "Default Web Site/xxx".

### ISSUE THREAD

**Issue by linkxu1989** [ShiWei-L/NlogDashboard#73]
Right here wait for your answer.
Could not found JS with 404 when published to IIS "Default Web Site/xxx".

**Comment by realLiangshiwei** [comment]
Do not open a new issue.
Discussed in https://github.com/realLiangshiwei/LogDashboard/issues/72

See: https://github.com/realLiangshiwei/LogDashboard/issues/72#issuecomment-826461352
