### ISSUE TITLE
AbpVＮext集成后可以进入页面但是无法查询也无法看详情

### ISSUE THREAD

**Issue by OldKing-lion** [ShiWei-L/NlogDashboard#74]
![image](https://user-images.githubusercontent.com/13028615/120949860-0c390b00-c778-11eb-8a9d-5417acbf6ac1.png)
![image](https://user-images.githubusercontent.com/13028615/120949885-1b1fbd80-c778-11eb-993f-393edeff5ea1.png)
![image](https://user-images.githubusercontent.com/13028615/120949895-22df6200-c778-11eb-82fb-64d30745d56f.png)

代码集成是根据文档来的：
![image](https://user-images.githubusercontent.com/13028615/120949906-2ffc5100-c778-11eb-98b3-6036755370b4.png)
![image](https://user-images.githubusercontent.com/13028615/120949918-368ac880-c778-11eb-859b-27d1c422981d.png)
![image](https://user-images.githubusercontent.com/13028615/120949929-3ee30380-c778-11eb-94d6-14113d047da3.png)

**Comment by realLiangshiwei** [comment]
I will check it out

**Comment by realLiangshiwei** [comment]
https://github.com/realLiangshiwei/LogDashboard/commit/75fe55e9ee845a7524724bea149490e0d61b649e
