### ISSUE TITLE
页面样式文件本地是好的，服务器CSS请求不到是什么问题

### ISSUE THREAD

**Issue by ByZhouhang** [ShiWei-L/NlogDashboard#80]
![微信图片_20210915223550](https://user-images.githubusercontent.com/43258053/133453899-b1a72b2f-92e4-47a5-babe-19135b5ff092.png)

**Comment by ByZhouhang** [comment]
服务器端IIS 设置了虚拟目录  /api    请求dashboard时带上了/api，  然后自动的css  js  请求 没有带上/api前缀，有办法解决么？

**Comment by realLiangshiwei** [comment]
已关闭的issue有解决方案
