### ISSUE TITLE
点击Information级别日志的”详情“会报错，点击Error级别的详情就没有问题

### ISSUE THREAD

**Issue by LiuXigang** [ShiWei-L/NlogDashboard#81]
会报以下错误
![image](https://user-images.githubusercontent.com/32047498/135233920-b267d1fd-7c12-47b8-9699-9fb3fae858e8.png)

点击以下按钮
![image](https://user-images.githubusercontent.com/32047498/135234406-99f47358-5510-4a69-bf41-0c2b33fd109e.png)
![image](https://user-images.githubusercontent.com/32047498/135234531-9b4c68eb-eaf7-4659-aaa4-4153375925b6.png)

**Comment by realLiangshiwei** [comment]
我会考虑在国庆重构项目，感谢支持
