### ISSUE TITLE
首页最近十条有时排序不对

### ISSUE THREAD

**Issue by lovepoco** [ShiWei-L/NlogDashboard#83]
2021-10-31 22:00:00的日志排到了2021-11-21 00:34:00的前面，且2021-11-21 00:34:00排到了最后

**Comment by realLiangshiwei** [comment]
请提供复现步骤

**Comment by realLiangshiwei** [comment]
重新打开如果有问题

**Comment by lovepoco** [comment]
环境是Ubuntu 9.3.0，组件版本1.4.8
日志输出组件是NLog
日志输出格式是
  xsi:type="file" name="file" fileName="${basedir}/logs/${shortdate}.log"
           layout="${longdate}||${level}||${logger}||${message}||${exception:format=ToString:innerFormat=ToString:maxInnerExceptionLevel=10:separator=\r\n}||end"
