### ISSUE TITLE
修改Pathmatch样式丢失

### ISSUE THREAD

**Issue by OldKing-lion** [ShiWei-L/NlogDashboard#90]
app.UseLogDashboard("/logs");
修改地址后：
![image](https://user-images.githubusercontent.com/13028615/153346526-960b0d53-4bac-47df-818d-45a49bf8c347.png)

修改地址前:
![image](https://user-images.githubusercontent.com/13028615/153346697-f144d3bd-33c8-499f-b888-e98dffc54e60.png)

**Comment by realLiangshiwei** [comment]
See https://github.com/realLiangshiwei/LogDashboard/issues/72

**Comment by OldKing-lion** [comment]
不对啊，我还没有发布，我本地IIS Express,路径改为/logs，就乱了。我这个路径改的是对的啊

**Comment by realLiangshiwei** [comment]
和发布没有关系，你改了路径options也要改
https://github.com/realLiangshiwei/LogDashboard/issues/72#issuecomment-826461352

**Comment by OldKing-lion** [comment]
我知道了，看了下路径试出来了，两边都要改。#72 那个我没看明白

**Comment by OldKing-lion** [comment]
谢谢
