### ISSUE TITLE
日志重复

### ISSUE THREAD

**Issue by tangxiaoqi-tangxiao** [ShiWei-L/NlogDashboard#93]
我发现我每一条日志都是重复
![C6P8VT@XIM{BU5@Y02{}D4M](https://user-images.githubusercontent.com/54069236/156319173-2c98470e-1935-4b06-a253-d6bbeff28c52.png)
的，我想知道是什么原因，我log4net配置用的是官方文档提供的

**Comment by realLiangshiwei** [comment]
解决了吗
