### ISSUE TITLE
日志按周查询异常

### ISSUE THREAD

**Issue by 2505253862** [ShiWei-L/NlogDashboard#98]
handle/logchart/weeklogchart.cs   下面的方法在按周抓取日志信息时逻辑有问题
public async Task<GetLogChartsOutput> GetCharts<T>(IRepository<T> repository) where T : class, ILogModel
{
            var now = DateTime.Now;
            var dayOfWeek = (int)now.DayOfWeek;
            dayOfWeek = dayOfWeek == 0 ? 6 : dayOfWeek == 6 ? 0 : dayOfWeek;  //**这里只是单纯的交换了周六和周日的DayOfWeek**
            //dayOfWeek = dayOfWeek == 0 ? 6 : dayOfWeek - 1;
            …………
}

**Comment by realLiangshiwei** [comment]
目前的版本打算归档，所以就不修复了，以接下来的新版本为主
